-- Table: public.efos_app_efo

-- DROP TABLE IF EXISTS public.efos_app_efo;

CREATE TABLE IF NOT EXISTS public.efos_app_efo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rfc character varying(13) COLLATE pg_catalog."default" NOT NULL,
    social_reason text COLLATE pg_catalog."default" NOT NULL,
    fiscal_situation character varying(3) COLLATE pg_catalog."default" NOT NULL,
    sat_presumtion_date date,
    dof_presumtion_date date,
    sat_definitive_date date,
    dof_definitive_date date,
    sat_distorted_date date,
    dof_distorted_date date,
    sat_favorable_ruling_date date,
    dof_favorable_ruling_date date,
    sat_presumtion_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    dof_presumtion_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    sat_definitive_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    dof_definitive_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    sat_distorted_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    dof_distorted_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    sat_favorable_ruling_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    dof_favorable_ruling_file_no character varying COLLATE pg_catalog."default" NOT NULL,
    sat_presumtion_file_date date,
    dof_presumtion_file_date date,
    sat_definitive_file_date date,
    dof_definitive_file_date date,
    sat_distorted_file_date date,
    dof_distorted_file_date date,
    sat_favorable_ruling_file_date date,
    dof_favorable_ruling_file_date date,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    CONSTRAINT efos_app_efo_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.efos_app_efo
    OWNER to postgres;

-- Table: public.efos_app_persondetail

-- DROP TABLE IF EXISTS public.efos_app_persondetail;

CREATE TABLE IF NOT EXISTS public.efos_app_persondetail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rfc character varying(13) COLLATE pg_catalog."default" NOT NULL,
    social_reason text COLLATE pg_catalog."default" NOT NULL,
    date_published date,
    type_of_person character varying(1) COLLATE pg_catalog."default" NOT NULL,
    state character varying COLLATE pg_catalog."default" NOT NULL,
    assumption character varying(14) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    CONSTRAINT efos_app_persondetail_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.efos_app_persondetail
    OWNER to postgres;

-- Table: public.efos_app_cancellation

-- DROP TABLE IF EXISTS public.efos_app_cancellation;

CREATE TABLE IF NOT EXISTS public.efos_app_cancellation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rfc character varying(13) COLLATE pg_catalog."default" NOT NULL,
    social_reason text COLLATE pg_catalog."default" NOT NULL,
    type_of_person character varying(1) COLLATE pg_catalog."default" NOT NULL,
    state character varying COLLATE pg_catalog."default" NOT NULL,
    date_published date,
    amount numeric(15,3) NOT NULL,
    cancel_reason character varying(4) COLLATE pg_catalog."default" NOT NULL,
    cancellation_date date,
    CONSTRAINT efos_app_cancellations_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.efos_app_cancellation
    OWNER to postgres;

-- Table: public.efos_app_art74reduction

-- DROP TABLE IF EXISTS public.efos_app_art74reduction;

CREATE TABLE IF NOT EXISTS public.efos_app_art74reduction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rfc character varying(13) COLLATE pg_catalog."default" NOT NULL,
    social_reason text COLLATE pg_catalog."default" NOT NULL,
    type_of_person character varying(1) COLLATE pg_catalog."default" NOT NULL,
    state character varying COLLATE pg_catalog."default" NOT NULL,
    date_published date,
    amount numeric(15,3) NOT NULL,
    authorization_date date,
    CONSTRAINT efos_app_art74reductions_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.efos_app_art74reduction
    OWNER to postgres;