# Generated by Django 4.2.5 on 2023-10-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efo',
            name='dof_definitive_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_definitive_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_definitive_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_distorted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_distorted_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_distorted_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_favorable_ruling_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_favorable_ruling_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_favorable_ruling_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_presumtion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_presumtion_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='dof_presumtion_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_definitive_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_definitive_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_definitive_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_distorted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_distorted_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_distorted_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_favorable_ruling_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_favorable_ruling_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_favorable_ruling_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_presumtion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_presumtion_file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='sat_presumtion_file_no',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='efo',
            name='state',
            field=models.CharField(blank=True, choices=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA CALIFORNIA', 'Baja California'), ('BAJA CALIFORNIA SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CIUDAD DE MEXICO', 'Ciudad De Mexico'), ('COAHUILA DE ZARAGOZA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('MEXICO', 'Estado de México'), ('MICHOACAN DE OCAMPO', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO LEON', 'Nuevo Leon'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Queretaro'), ('QUINTANA ROO', 'Quintana Roo'), ('SAN LUIS POTOSI', 'San Luis Potosi'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ DE IGNACIO DE LA LLAVE', 'Veracruz'), ('YUCATAN', 'Yucatan'), ('ZACATECAS', 'Zacatecas')]),
        ),
        migrations.AlterField(
            model_name='efo',
            name='type_of_person',
            field=models.CharField(blank=True, choices=[('M', 'Persona Moral'), ('F', 'Persona Física')], max_length=1),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='assumption',
            field=models.CharField(blank=True, choices=[('FIRME', 'Firme'), ('EXIGIBLE', 'Exigible'), ('NO LOCALIZADO', 'No Localizado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='date_published',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='state',
            field=models.CharField(blank=True, verbose_name=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA CALIFORNIA', 'Baja California'), ('BAJA CALIFORNIA SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CIUDAD DE MEXICO', 'Ciudad De Mexico'), ('COAHUILA DE ZARAGOZA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('MEXICO', 'Estado de México'), ('MICHOACAN DE OCAMPO', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO LEON', 'Nuevo Leon'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Queretaro'), ('QUINTANA ROO', 'Quintana Roo'), ('SAN LUIS POTOSI', 'San Luis Potosi'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ DE IGNACIO DE LA LLAVE', 'Veracruz'), ('YUCATAN', 'Yucatan'), ('ZACATECAS', 'Zacatecas')]),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='type_of_person',
            field=models.CharField(blank=True, choices=[('M', 'Persona Moral'), ('F', 'Persona Física')], max_length=1),
        ),
    ]
