# Generated by Django 4.2.5 on 2023-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efos_app', '0002_alter_efo_dof_definitive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efo',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
    ]
