# Generated by Django 4.2.5 on 2023-10-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efos_app', '0005_remove_efo_state_remove_efo_type_of_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art74Reductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('social_reason', models.TextField(max_length=250)),
                ('type_of_person', models.CharField(blank=True, choices=[('M', 'Persona Moral'), ('F', 'Persona Física')], max_length=1)),
                ('state', models.CharField(blank=True, verbose_name=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA CALIFORNIA', 'Baja California'), ('BAJA CALIFORNIA SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CIUDAD DE MEXICO', 'Ciudad De Mexico'), ('COAHUILA DE ZARAGOZA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('MEXICO', 'Estado de México'), ('MICHOACAN DE OCAMPO', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO LEON', 'Nuevo Leon'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Queretaro'), ('QUINTANA ROO', 'Quintana Roo'), ('SAN LUIS POTOSI', 'San Luis Potosi'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ DE IGNACIO DE LA LLAVE', 'Veracruz'), ('YUCATAN', 'Yucatan'), ('ZACATECAS', 'Zacatecas')])),
                ('date_published', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('authorization_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancellations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('social_reason', models.TextField(max_length=250)),
                ('type_of_person', models.CharField(blank=True, choices=[('M', 'Persona Moral'), ('F', 'Persona Física')], max_length=1)),
                ('state', models.CharField(blank=True, verbose_name=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA CALIFORNIA', 'Baja California'), ('BAJA CALIFORNIA SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CIUDAD DE MEXICO', 'Ciudad De Mexico'), ('COAHUILA DE ZARAGOZA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('MEXICO', 'Estado de México'), ('MICHOACAN DE OCAMPO', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO LEON', 'Nuevo Leon'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Queretaro'), ('QUINTANA ROO', 'Quintana Roo'), ('SAN LUIS POTOSI', 'San Luis Potosi'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ DE IGNACIO DE LA LLAVE', 'Veracruz'), ('YUCATAN', 'Yucatan'), ('ZACATECAS', 'Zacatecas')])),
                ('date_published', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cancel_reason', models.CharField(choices=[('C', 'Cancelados'), ('INCO', 'Cancelados por incosteabiliad'), ('INSO', 'Cancelados por insolvencia')], max_length=4)),
                ('cancellation_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='assumption',
            field=models.CharField(blank=True, choices=[('FIRMES', 'Firme'), ('EXIGIBLES', 'Exigible'), ('NO LOCALIZADOS', 'No Localizado'), ('SENTENCIAS', 'Sentencias')], max_length=14),
        ),
    ]
