# Generated by Django 4.2.5 on 2023-10-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efos_app', '0006_art74reductions_cancellations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art74Reductions',
            new_name='Art74Reduction',
        ),
        migrations.RenameModel(
            old_name='Cancellations',
            new_name='Cancellation',
        ),
    ]
