# Generated by Django 4.2.5 on 2023-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efos_app', '0009_alter_cancellation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art74reduction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
